### ISSUE TITLE
Can't delete the mask symbols,Suggest to modify

### ISSUE THREAD

**Issue by angular-moon** [wender/angular-simple-input-mask#2]
> for (var nmI = 0, mI = 0; mI < format.length;) {
>       if (!value[nmI]) {
>             break;
> }
> if (format[mI].match(/\D/)) {
>        newValue += format[mI];
> } else {
>        newValue += value[nmI];
>         nmI++;
>       }
>    mI++;
> }

**Comment by wender** [comment]
Thanks @angular-moon I've just pushed your suggestion on 0.0.8
