### ISSUE TITLE
Mudar dinamicamente a mascara

### ISSUE THREAD

**Issue by jonyw4** [wender/angular-simple-input-mask#3]
Essa é uma função simples, porem de extrema necessidade, principalmente em campos que mudam de acordo com a necessidade do negocio. Percebi também que praticamente nenhum projeto de mascara para angularJs tem essa função, e o que tem precisa do jQuery para funcionar.

**Comment by wender** [comment]
Obrigado pela sugestão @jonyw4 aceitei seu pull request, agora estamos na versão 0.0.8
